"""Compile the reviewed relic design into C++ definitions and bilingual text resources.

This does not change existing ordinary relics or update the approved design workbooks.
The workbooks are exported only after runtime/visual validation has passed.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "docs/design/2026-09-10-relic-redesign/relic-design.json"
OUTPUT = ROOT / "Source/GameXXK/Private/GameXXKRelicSynergyDefinitions.inl"
LANGUAGES = ROOT / "Content/Localization/GameXXK/strings.json"
TRIGGERS = {"battle_start": "BattleStart", "round_start": "PlayerRoundStart",
            "round_end": "PlayerRoundEnd", "active_card": "CardPlayed", "damage_taken": "DamageTaken"}


def render(design):
    rows = ["// Generated by scripts/generate_gamexxk_relic_redesign.py from the authored relic design."]
    for relic in design["relics"]:
        rows.append('MakeSynergy(TEXT("{slug}"), EGameXXKCardQuality::{quality}, EGameXXKRelicTrigger::{trigger}, '
                    'TEXT("{effect}"), {primary}, {secondary}),'.format(**{**relic, "trigger": TRIGGERS[relic["trigger"]]}))
    return "\n".join(rows) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    design = json.loads(DESIGN.read_text(encoding="utf-8-sig"))
    generated = render(design)
    language = json.loads(LANGUAGES.read_text(encoding="utf-8-sig"))
    existing = {e["key"]: e for e in language["entries"] if e.get("namespace", "GameXXK") == "GameXXK"}
    required = []
    for relic in design["relics"]:
        for field, suffix in (("name", "Name"), ("description", "Description")):
            required.append({"key": relic["id"] + "." + suffix, **relic[field]})
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("The compiled relic definitions do not match the authored design.")
        if any(existing.get(e["key"]) != e for e in required):
            raise SystemExit("The relic translations do not match the authored design.")
        print("Relic definitions and bilingual resources match the authored design (runtime verification is separate).")
        return
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    required_keys = {e["key"] for e in required}
    language["entries"] = [e for e in language["entries"] if e["key"] not in required_keys] + required
    LANGUAGES.write_text(json.dumps(language, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {len(design['relics'])} relic definitions and {len(required)} bilingual entries.")


if __name__ == "__main__":
    main()
