from main_story_authoring import n, chapter, option

CHAPTER = chapter("S05", "苍山·登顶以后嘴也别停", "最后一段路遇见琼幺儿，风雪替豪言壮语降温。把旧抄本与亲见的山川合在一起，给这趟求证留个能继续往下写的结尾。", "S05-10", [
    n("S05-01", "苍山脚下", "苍山把云顶在头上，幽白把气势顶在脸上。你把衣领拢紧，决定先看看哪一样更抗风。", "确认上山路线与风雪变化", [
        ("hero", "前面就是苍山？看着比旧图上画得高。"),
        ("you_bai", "纸张有限，名山适当收敛了一下。"),
        ("hero", "山没收敛，我的腿倒先谦虚了。"),
        ("narrator", "山脚有人行旧道通往古寨，高处的雪线时隐时现。你们决定先问熟悉山路的人。"),
        ("you_bai", "这回本座赞成先问再走。经验之谈。"),
        ("hero", "进步很大，天台山那座桥听了都欣慰。"),
    ], "确认先沿旧道到古寨问路，准备应对高处风雪。",
    "At the foot of Cangshan, the exact hero tucks his grey-blue collar against a light mountain wind while consulting the old map. Youbai hovers beside his face, attempting a dignified expression despite being blown slightly sideways. A clear old path leads toward a small distant mountain village, with a faint snow line above. They are still safely at the foothill, not already at the summit."),
    n("S05-02", "苗族古寨", "寨里姑娘听完你的来意，先看了看图，又看了看幽白，表示这趟队伍的热闹程度已经达标。", "结识琼幺儿，询问鹰喙岩与上山路", [
        ("qiong_yao_er", "我是琼幺儿。你们去找鹰喙岩？先别让这团火替你们决定方向。"),
        ("you_bai", "本座的名声，怎么已经传到这里了？"),
        ("hero", "不是名声，是你刚才盯着雪峰说‘那条近’。"),
        ("qiong_yao_er", "近不近看路，险不险看天。等风小些，我把认岩和过潭的线索讲给你们。"),
        ("hero", "好。有当地人带路，心里踏实。"),
        ("qiong_yao_er", "我先负责讲清楚，你负责认真听。别给自己的勇气加戏。"),
    ], "结识琼幺儿，得到等待风雪减弱与核对鹰喙岩的指引。",
    "At the open porch of a mountain village, the exact red-orange-jacketed Qiong Yaoer with cream beaded cap, ochre skirt, braid and bronze bell greets the hero with a confident teasing smile. Youbai hovers between them looking affronted. She indicates the distant rock landmarks rather than offering a weapon or changing party equipment. Sparse timber, hanging plain cloth and a pale mountain backdrop; no active snow emergency.", all=["S05-01"]),
    n("S05-03", "暴风避雪", "风雪一紧，三人躲到檐下。幽白说高手懂得审时度势，你说普通人也懂得不站着挨冻。", "等待风势减弱，核对出发时机", [
        ("narrator", "刚才山风骤紧，三人退回结实屋檐下。旧图被压在石块下，谁也没急着往白茫茫里走。"),
        ("you_bai", "此乃以静制动。"),
        ("hero", "我叫它先躲躲。"),
        ("qiong_yao_er", "两个名字都行，别给等天气这件事吵出个门派。"),
        ("narrator", "片刻后，近处松梢不再急摇，石阶边线重新可辨。琼幺儿示意可以沿旧道谨慎前行。"),
        ("hero", "风肯讲道理了，我们也别突然不讲。"),
    ], "安全避过骤紧风雪，在旧道可辨后继续行程。",
    "Hero, exact Qiong Yaoer and Youbai stand safely under a sturdy mountain-village porch after the worst gust has passed. The map lies intact under a small stone on a bench, and the old stone path outside is visible again through easing snow. Hero warms his hands, Qiong calmly gestures toward the now-clear path, and Youbai pretends this pause was profound strategy. No blizzard exposure or fallen character.", all=["S05-02"]),
    n("S05-04", "定位鹰喙岩", "两块岩石都觉得自己像鹰，真正那块倒没空争辩，安安静静对着旧道。", "结合岩形、旧道与松树位置认出鹰喙岩", [
        ("qiong_yao_er", "鹰喙岩向外挑出一角，下面接旧石道，旁边有一棵弯向山谷的老松。三样合起来认。"),
        ("you_bai", "那边那块也像鹰。"),
        ("hero", "你看馒头也像名山，先按线索来。"),
        ("narrator", "左前方岩角外挑，旧道贴着岩下延伸，老松向谷侧弯着。右方孤石形似鸟头，四周却没有路。"),
        ("qiong_yao_er", "像什么只是第一眼，能不能与地势对上才要紧。"),
    ], "认出连接旧道与老松的鹰喙岩，安全定位后续路线。",
    "On a safe broad mountain path, the hero matches his map with a distinctive outward-projecting rock above the old stone trail and a bent pine leaning toward the valley. Exact Qiong Yaoer points out the three matching features; Youbai reluctantly turns away from a distant useless bird-shaped isolated stone. All characters stand on secure ground, the solved landmark is clear, no cliff leap or false route taken.", kind="Investigation", all=["S05-03"],
    options=[option("认左前方同时对应旧道和老松的外挑岩角", True, "岩形、道路与老松三处吻合，鹰喙岩定位成功。"), option("只挑最像鸟头的右方孤石", False, "它像鹰不假，可它旁边没路。别把欣赏奇石当赶路方案。"), option("听幽白选，看它哪边夸得响", False, "琼幺儿轻轻摇铃：这条线索只有音量，没有方向。")],
    hints=["把岩石形状与旁边的道路、老松一起核对。", "真正的鹰喙岩同时有外挑岩角、岩下旧道和向山谷弯的老松。", "选择‘认左前方同时对应旧道和老松的外挑岩角’。"]),
    n("S05-05", "洗马潭", "潭面照着云，你的旧图照着过去。幽白说二者都很有意境，琼幺儿说看路时先别忙着作诗。", "核对潭边旧路与稳定通行处", [
        ("hero", "潭边这一段，旧图画得太直，实际得沿石岸绕一下。"),
        ("qiong_yao_er", "贴着稳固的旧道走，别贪近踩薄雪。山路最爱教嘴硬的人重新做人。"),
        ("you_bai", "本座没有脚，暂不参加这门课程。"),
        ("hero", "那麻烦你照清楚，给有脚的同学一点帮助。"),
        ("narrator", "三人核对潭边地势，正要沿旧道前行，前方转折处忽然传来兽群逼近的动静。"),
    ], "修正潭边绕行路线，发现前方有需要处理的险情。",
    "By a quiet high mountain tarn, hero marks the curved stone-bank route on his map while exact Qiong Yaoer indicates firm old-path footing. Youbai provides a modest guiding glow near the stones. Thin snow lies only off the secure path, clouds reflect softly in the water. The group has finished checking the route and turns alertly toward a distant sound; no rescue outcome or animal attack yet.", all=["S05-04"]),
    n("S05-06", "英雄救美", "兽群堵住了转折处，琼幺儿护着旧道边的落脚点。幽白催你动手，你表示这次终于轮到正经出力。", "进入2-3，在剧情问号处击退兽群，与琼幺儿安全脱险", [
        ('qiong_yao_er', '前边窄道堵了，一头灰狼，一只豪猪。稳石在左，别往碎石上冲。'),
        ('hero', '今日英雄救美，先保证英雄不滑成笑话。'),
        ('you_bai', '本座先把这句话记下。真滑了，好知道笑哪一句。'),
        ('qiong_yao_er', '我看住落脚点。等你把前路清开，我们再相互接应。'),
        ('hero', '好，先备齐再上。英雄称号晚点领，路得先走稳。'),
    ], "兽群被击退，主角与琼幺儿互相照应安全脱险，前路恢复通行。",
    "After the successful rescue, the exact hero sits firmly on a broad safe rock catching his breath while exact Qiong Yaoer stands securely beside him, lightly straightening his slipped backpack strap with a teasing smile. Youbai floats nearby, amused but relieved. All feet and bodies are safely on stable ground, no person dangling over a cliff and no current attack. A quiet highland tarn and a little snow establish the scene; mutual help rather than a helpless damsel pose.", kind="JourneyBattle", all=["S05-05"],
    hints=["救援需要在对应关卡的剧情问号处完成真实战斗。", "使用当前旅程的队伍和卡组，获胜后继续与琼幺儿的剧情。", "从本节点进入2-3，在剧情问号处赢下任务战斗。"],
    enemies=['Enemy.Ch2.GrayWolf', 'Enemy.Ch2.Porcupine'],
    after_battle=[
        ('narrator', '兽群退入山影。你撑竿站稳，琼幺儿扶了一下你的肩，把你接过松动的石沿。'),
        ('qiong_yao_er', '好了。人都站住了，哪位英雄刚才差点把包留在原地？'),
        ('hero', '包是诱敌之计。人不是，幸亏你接得快。'),
        ('you_bai', '本座记明白了：今日互相救美，双方都有出力。'),
        ('qiong_yao_er', '那就谁也别抢功。前路还长，互相搭把手。'),
    ]),
    n("S05-07", "坚持前行", "险情过去，山顶还在前面。你把旧图重新摊开，发现自己已经不再只等它给答案。", "整理继续登顶的理由与可靠路线", [
        ("hero", "都走到这里了，我想把最后这一段亲眼看清。"),
        ("you_bai", "很好，少侠当有此志。"),
        ("hero", "主要是前面改了这么多，总不能最后一笔又靠猜。"),
        ("qiong_yao_er", "那就沿已经核实的旧道继续。坚持不是跟险处较劲，是知道自己为什么往前走。"),
        ("hero", "听见了，稳稳地走。豪言壮语先省着，到山顶再用。"),
    ], "确定沿已核实的安全旧道继续登顶。",
    "On the safe upper mountain trail, hero tightens his bamboo basket strap with renewed determination and points along the already-checked route. Exact Qiong Yaoer stands beside him with a calm approving smile; Youbai hovers with a smaller, more genuine look of pride. Broad pale peaks and open clouds, optimistic steady progress, no reckless leap or charging pose.", all=["S05-06"], optional=True, inside=True),
    n("S05-08", "暗生悔意", "你承认刚才有一瞬间想下山。幽白还没来得及端架子，琼幺儿先把这句话接住了。", "正视害怕，调整步调后继续", [
        ("hero", "说实话，方才那阵动静一来，我脑子里已经开始规划回家的饭了。"),
        ("you_bai", "这……倒也不算没有规划。"),
        ("qiong_yao_er", "怕很正常。先停一停，缓过来，再按能确认的路走。没人规定求真必须全程嘴硬。"),
        ("hero", "那我承认，刚才确实慌。现在好多了。"),
        ("you_bai", "本座也承认，方才飘得稍微快了些。"),
        ("hero", "懂了，咱们一个战术坐下，一个战术飘远。缓好了，继续。"),
    ], "承认并平复险后的害怕，选择以更稳妥的步调继续前行。",
    "At a sheltered safe rest rock after the rescue, hero sits with a rueful embarrassed smile while exact Qiong Yaoer offers calm reassurance and Youbai hovers slightly sheepishly. The map stays open and intact across hero's knees. No one is abandoning equipment or turning permanently back; this is a brief honest pause before continuing. Soft mountain wind and reassuring open paper space, warm understated humor.", all=["S05-06"], optional=True, inside=True),
    n("S05-09", "幽白释疑", "几章所见终于拼到一起。幽白坦白，自己守了许久的并非一张永远正确的图，而是一件需要人继续做的事。", "理解幽白守图的心愿，核对全程证据", [
        ("hero", "幽白，你明知抄图会有漏笔，怎么一开始还那么笃定？"),
        ("you_bai", "守得久了，总想替它多说两句。再说，本座也有面子。"),
        ("hero", "你本体除了脸，确实也没剩多少地方能放。"),
        ("you_bai", "……但这一路，本座看明白了。守图，不该只守旧墨，还得等愿意亲自看、认真改的人。"),
        ("qiong_yao_er", "你们把桥、溪、田渠和寨道都问过、走过。这些才是能留下来的东西。"),
        ("hero", "那最后这笔，就写给后面还要走路的人。哪天他们发现错了，也尽管改。"),
        ("you_bai", "可以。改的时候，对本座客气一点便是。"),
    ], "明白幽白守图的心愿，将六章证据统一为可继续订正的舆图。",
    "On a calm upper-mountain ledge, hero and exact Qiong Yaoer hold different edges of the same developing map while the small blue-lavender Youbai hovers close, unusually sincere with just a trace of stubborn pride. The paper shows a continuous pictorial network of mountains and waterways, no readable writing or glowing runes. An intimate revelation and shared understanding before the summit, not a transformation into a human or a farewell death.", any=["S05-07", "S05-08"], inside=True, mood="Warm, sincere resolution with a light comic undercurrent; the spirit remains alive and present."),
    n("S05-10", "苍山之巅", "站到山顶再看舆图，纸上已经不只剩旧墨。幽白想发表感言，你决定这次让它说完。", "完成苍山末段订正，为行旅续志", [
        ("narrator", "苍山云海展开在眼前。旧抄本与一路补记终于对合，溪流、村寨、山道各归其位。"),
        ("hero", "祖父说图上不明白的地方，要亲眼看看。现在总算能回他一句：看过了，也改过了。"),
        ("qiong_yao_er", "这趟走得值。以后还有人沿着它来，少走冤枉路，多看些真山水。"),
        ("you_bai", "本座宣布，此行圆满。少侠腿脚勤勉，偶有顶嘴，整体值得——"),
        ("hero", "前辈，感言控制一下。山顶风大，不包返场。"),
        ("you_bai", "……值得同行。"),
        ("narrator", "你在卷尾添下一句自己的话：先贤之路，非独山水，亦在求真。余下的空白，留给下一段旅程。"),
    ], "苍山末段订正完成，六章主线收束，舆图留下继续求证的余白。",
    "At the broad safe summit above a tranquil Cangshan cloud sea, the hero displays the completed travel map between himself and exact Qiong Yaoer, both smiling with earned quiet joy. Youbai floats proudly and affectionately beside the map, still a small blue-lavender bodiless flame. A plain weathered stone stele sits nearby without readable characters. The map contains simple coherent mountain and river drawing marks, not UI nodes or text. Expansive warm light, spacious ink peaks, celebratory but gentle and slightly playful; everyone alive and safely together.", all=["S05-09"], inside=True, mood="Open, warm accomplishment and affectionate comedy, with room for the next journey."),
    n("S05-11", "苗家姑娘", "琼幺儿的铃声清脆，指路也清楚。幽白问铃有何神通，她说最大的神通是让话多的人知道该停了。", "了解琼幺儿与当地识路经验", [
        ("you_bai", "姑娘这铃，可辨山灵、引云气？"),
        ("qiong_yao_er", "能提醒走散的人，也能提醒话多的人。"),
        ("hero", "这件法器很适合我们队。"),
        ("you_bai", "本座怎么觉得，第二项功能有所针对？"),
        ("qiong_yao_er", "看天色、听风、认旧路，都是人一趟趟走出来的。你们肯把这些写清，我就愿意多讲些。"),
        ("hero", "那就多记几笔。铃声留着提醒我们，嘴别跑到脚前头去。"),
    ], "听取琼幺儿的识路经验，建立同行默契。",
    "At the mountain village porch, exact Qiong Yaoer playfully lifts her small bronze hand bell as hero smiles in understanding and Youbai looks theatrically targeted by the joke. Her cream beaded cap, braid, red-orange jacket, ochre skirt and trailing scarf remain exact. A relaxed introduction and sharing of local knowledge, no spell explosion, no rescue yet, no extra companions.", all=["S05-02"], optional=True),
])

next(node for node in CHAPTER["nodes"] if node["id"] == "S05-09")["original_title"] = "月玉合谲"
