from main_story_authoring import n, chapter, option

CHAPTER = chapter("S00", "天台山·祖传也会指错路",
"一阵山风吹醒守图灵，也吹破了祖传地图绝不会错的体面。救下的不是一卷圣旨，而是一张允许继续改的图。", "S00-06", [
    n("S00-01", "天台山脚", "你还在和车夫讲价，祖传地图已经抢先上山。第一件江湖大事：追上自己的行程。", "问清上山方向，整理旧抄图", [
        ("narrator", "天台山脚，你展开祖父留下的旧图，打算先找条体面的上山路。"),
        ("driver", "沿溪，过桥，往国清寺去。山路不收车钱，专收腿。"),
        ("hero", "你把这话写在车上，生意还能剩几成？"),
        ("narrator", "你转身讲价的工夫，一阵山风从卷轴底下钻过，把整张图托了起来。"),
        ("hero", "哎！我还没出发，路线怎么先跑了！"),
        ("driver", "好图，有自己的打算。"),
        ("narrator", "你拎着竹竿追向浅溪。车夫没追，先替你按住了滚到脚边的墨盒。"),
        ("driver", "方向记牢了再追！图捞回来，膝盖可没地方补。"),
    ], "已问清沿溪上山的方向，旧图被风吹向浅溪。",
    "A brisk low diagonal action shot at the Tiantai stream bank. The hero lunges sideways with his bamboo pole after a broad wind-lifted paper map, one foot braced safely on a rock. The coachman at the opposite near corner calmly pins the rolling ink box beneath his shoe and calls after him. The map and their opposed gazes connect the whole frame. A large clean wind curve, two pale mountain shapes and very few props. No spirit, no carriage, no drowning or lost scroll.",
    highlight="路线比人先出发：主角飞身追图，车夫稳稳替他踩住墨盒。",
    camera="low diagonal action, near/far counterpoint",
    facts=["主角已问清沿溪上山方向。", "幽白尚未现身；旧图正被风吹向可捞回的浅溪，没有毁坏。"]),

    n("S00-02", "获得卷轴", "竹竿挑回了湿图，也挑出一团满肚子官腔的火。你差点当场认了个缩水祖父。", "拾回卷轴，认识幽白", [
        ("hero", "才出门就洗祖业，祖父知道了怕是要冒烟。"),
        ("narrator", "竹竿一挑，湿卷摊开。蓝紫色灵火从两条旧批注之间蹿出来，正撞上你的鼻尖。"),
        ("hero", "祖父？你怎么……缩水了？"),
        ("you_bai", "认亲先停！本座幽白，守图之灵，不负责给你添辈分。"),
        ("hero", "那你从我祖父的图里出来，总得有个说法。"),
        ("you_bai", "这卷图历代有人抄，也历代有人改。本座看着他们落笔，睡醒一觉，竟轮到你来泡澡。"),
        ("narrator", "你翻到卷背，果然看见几种深浅不同的旧笔迹。幽白挡在最歪的一笔前，催你赶路。"),
        ("you_bai", "先去国清寺核对旧路！还有，别对着本座叫祖父，听着显老。"),
    ], "卷轴已拾回，幽白现身同行，决定前往国清寺核对旧路。",
    "Tight three-quarter character reveal at a shallow creek. The intact damp scroll is hooked on the hero's raised bamboo pole; a single bodiless blue-purple flame bursts from its fold close to his face. The hero jerks his head and shoulders back with a wonderfully mistaken look of recognition while the small spirit leans forward in affronted grandeur. Their two faces and the open roll dominate, no extra limbs on the spirit, only two clean water arcs. This is the startling first encounter, not a calm introduction after it.",
    all=["S00-01"], highlight="竹竿挑出一团火，主角脱口喊祖父，幽白当场炸毛。",
    camera="tight three-quarter reveal", mood="A startling reveal immediately punctured by ridiculous mistaken identity; bright, clean and playful."),

    n("S00-03", "越过山肩", "幽白刚宣布旧图绝不会错，桥就当着它的面掉了一块板。前辈的体面和你的脚，得先保一个。", "根据脚印与路标选择安全上山路", [
        ("you_bai", "前方过桥。这一段本座记得，闭着眼都——"),
        ("narrator", "咔。桥上最后一块松板翻了下去。你把抬起的脚收回来，幽白把没说完的话咽回去。"),
        ("hero", "闭着眼，都听得见它塌。"),
        ("you_bai", "桥没有认真执行地图。"),
        ("hero", "图全对，山河全责？这回先请脚底板表个态。"),
        ("narrator", "右边藤坡滑着青苔。左边松根石阶挂着旧青布，泥上留着新脚印；有人已经从那里上山。"),
        ("you_bai", "等会儿。新脚印旁没有折返的印子……这条应当走得通。"),
        ("hero", "这句算证据。前辈，再来两句这种的。"),
    ], "沿有新脚印的松根石阶安全越过山肩，记下断桥与绕行路。",
    "A high oblique view of the fork at the exact instant the false route loses authority. One large loose bridge plank flips downward in the far side of the composition. The hero plants his staff and draws his raised foot back onto solid ground, already turning his body toward the left stone stairs with a blue-cloth marker and clear fresh footprints. Youbai hangs frozen over the failed bridge approach, then follows the hero's gaze. No one falls or jumps. Use one bold plank shape, not debris particles.",
    kind="Investigation", all=["S00-02"], highlight="幽白的话没说完，桥板先给出了反对意见。",
    camera="high oblique fork with a sudden moving plank",
    options=[option("走挂青布、留有新脚印的松根石阶", True, "幽白这次看了脚印才点头。你们走上石阶，把断桥留在身后。"), option("相信祖传地图，从断桥跳过去", False, "幽白立刻拦住你：本座负责认路，不负责把人拼回去。"), option("沿满是青苔的藤坡直上", False, "你用竹竿一试，苔皮整片滑落。腿没有比竹竿多长一双眼。")],
    hints=["先看哪条路近期有人走过。", "青布石阶有新脚印，而且没有折返印；断桥和青苔坡都不稳。", "选择‘走挂青布、留有新脚印的松根石阶’。"]),

    n("S00-04", "初次战斗", "山客的手稿被兽群围住了。你以为它们要抢奇书，翻开纸背才发现：老人拿稿子包过芝麻饼。", "进入1-1，在剧情问号处击退拦路兽群", [
        ('narrator', '松根石阶尽头，一位山客气喘吁吁地跑来，怀里空得很有说服力。'),
        ('mountain_man', '少侠，前头石滩有两位不识字的书友，把我的手稿围住了！'),
        ('hero', '书友？'),
        ('mountain_man', '一只公鸡，一只黄鼠狼。它们看书不用眼，用嘴。'),
        ('you_bai', '本座听着，像是你的著作终于有了读者。'),
        ('mountain_man', '手稿背面包过芝麻饼！那是半辈子的路，不是半辈子的饼！'),
        ('hero', '你留在安全处指路。我去把手稿取回来，读者也劝退。'),
        ('you_bai', '先备好家伙再动身。江湖第一课，别让祖传地图输给蘸油手稿。'),
    ], "拦路兽群被击退，山客与手稿平安，获知国清寺仍存旧路记录。",
    "A decisive comic action keyframe during the manuscript rescue. The hero sweeps his bamboo staff across the frame to catch and lift three intact manuscript sheets away from the beast's reach, his torso twisting dynamically but his footing secure. The elderly mountain traveler on the other side opens a cloth bag wide to catch the rescued papers, his hat tilted by the rush. Youbai makes a bright bodiless blue-purple diversion from the opposite height. The paper wrapping reveals one simple sesame flatbread, making the animals' interest understandable. Keep the human relay and crossing diagonals as the focus; no gratitude lineup, no seated map reading, no gore. Necessary beast designs must match the stage's real roster if visible.",
    kind="JourneyBattle", all=["S00-03"], highlight="护的不是奇书秘宝，而是包过饼的半生手稿：挑纸、接稿、引兽三人同时动起来。",
    camera="wide decisive action with crossing diagonals", mood="Urgent slapstick with real care for the mountain traveler's irreplaceable notes.",
    hints=["这一段得实际进图，先护住山客和手稿。", "到1-1剧情问号，用当前队伍击退拦路兽群。", "在必经剧情问号完成任务战斗并获胜，手稿才算保住。"],
    enemies=['Enemy.Ch1.Rooster', 'Enemy.Ch1.Weasel'],
    after_battle=[
        ('narrator', '兽群终于退开。你用竹竿挑起散页，山客张开布袋接住，饼屑比掌声落得还响。'),
        ('mountain_man', '稿在，人也在。那两块饼就当稿费了。'),
        ('hero', '下回另找张油纸，别让读者吃到路线结局。'),
        ('you_bai', '本座负责照路，不负责给芝麻提亮。'),
        ('mountain_man', '国清寺还存着旧路记录。你们带图去对照，比听我这张饿嘴靠谱。'),
        ('hero', '好。先补图，再补午饭。'),
    ]),

    n("S00-05", "国清寺", "你带着断桥的疑问见住持。幽白想请一份‘绝不会错’的正本，住持却展开一张补丁摞补丁的旧图。", "请住持核对旧桥与山路记载", [
        ("you_bai", "请住持取正本来。抄本会错，正本总该稳当。"),
        ("narrator", "住持展开旧图，一层纸翻开，底下还有一层。桥的旧画、新画和绕行线，叠得像件百家衣。"),
        ("hero", "这正本，缝得挺勤。"),
        ("abbot", "桥毁过，溪涨过，路也改过。每来一个亲眼走过的人，便添一处。"),
        ("you_bai", "那……哪层才算祖宗定下的？"),
        ("abbot", "祖宗走过的那层。你今日走过的，也可以算一层。"),
        ("narrator", "幽白让开卷角，露出自己刚才死挡着的歪批注。住持确认旧桥已毁，松根石阶正是如今通行的路。"),
        ("hero", "明白了。敬重前人，不耽误把眼前这一笔画对。"),
    ], "住持确认旧桥已毁、新路已成，允许以实地证据补注抄图。",
    "An overhead-leaning close view of the reveal: the abbot lifts two broad hinged paper correction patches from an old courtyard map, exposing a crossed-out bridge and a clear hillside stair detour underneath. Across the table the hero leans forward with delighted realization, while Youbai physically yields the corner it was trying to obscure and looks caught out. Hands lift and hold the layered paper at different heights; all three faces are visible. Three large paper layers at most, no readable writing or second intact bridge, no polite document presentation pose.",
    all=["S00-04"], inside=True, highlight="所谓正本没有神谕，只有一层层被认真改过的补丁。",
    camera="high close reveal of lifted map layers", mood="A warm revelation that overturns authority without mocking the people who preserved the records."),

    n("S00-06", "获得天台山简图", "落笔前，幽白还想争一行署名。可它看见你认真划掉错路，忽然先替你照亮了那个空角。", "完成天台山路段的第一笔订正", [
        ("hero", "旧桥作废，石阶补上。这里留个空角，记谁见过、何时改过。"),
        ("you_bai", "空角先写本座指导有方。"),
        ("hero", "行。后面再添：一度坚持从断桥起飞。"),
        ("narrator", "幽白憋了半晌，把光挪到了你落笔的地方。那一条歪批注，在新路旁边变得不那么刺眼了。"),
        ("you_bai", "错路也留个记号。后来人一看，便不必再踩一回。"),
        ("abbot", "这句，才像个守图的。"),
        ("narrator", "你们补成天台简图。住持另取一页黄山暗溪记录：同一段水路，竟留下两种画法。"),
        ("hero", "前辈，下回争署名之前，咱俩先把两种里哪种不对找出来。"),
    ], "天台山简图已补全，取得黄山暗溪的后续线索。",
    "An intimate turning-point composition at the table edge. The hero's brush draws one confident correction line as the small bodiless Youbai deliberately moves its light away from its own grand corner and onto the hero's hand. The abbot's broad palm steadies the opposite paper edge. Hero and spirit exchange a brief unexpectedly sincere glance in the middle of their joke. A completed simple bridge-to-stair correction remains legible as pictorial marks; a folded next clue rests aside. Focus on the choice to help, not holding a finished map up for the viewer.",
    all=["S00-05"], inside=True, highlight="幽白第一次主动照着主角改错，争功的火变成了帮忙的光。",
    camera="intimate oblique close-up around the brush and three eyelines", mood="Quiet payoff after the chase and fight; affectionate, lightly comic sincerity."),

    n("S00-07", "客栈", "掌柜把旧桥改道说得云山雾罩，还想卖你一份保真路图。你一低头，发现证据就垫在他屁股底下。", "向掌柜核实山路与住店传闻", [
        ("innkeeper", "本店可添茶，也可问路。问路另有问路的价，保真另算。"),
        ("hero", "那你先把刚才两种相反的走法保成一种。"),
        ("you_bai", "本座赞成。收费可以分档，山路不该分身。"),
        ("narrator", "掌柜一挪凳子，凳脚露出半截旧桥栏杆，断口还留着熟悉的木榫。"),
        ("hero", "原来桥没退休，转来你家坐班了。"),
        ("innkeeper", "旧桥拆料做的！香客改走石阶之后，我这儿生意也跟着挪了门。"),
        ("narrator", "你让他指出改道的位置，又把桥料与沿途所见对上。掌柜把准备收钱的手改成了添茶。"),
        ("innkeeper", "这壶算我请。往后传闻多听，落笔前多看一眼——别学我，嘴比门路多。"),
    ], "从掌柜处核实改道传闻，学会把传闻和实地证据分开记。",
    "A low counter-height visual punchline in the mountain inn. The innkeeper tips his stool sideways, unexpectedly exposing a single large reused broken-bridge railing beneath it. The hero bends from the waist to inspect the unmistakable wooden joint and looks up with a dry grin; Youbai drifts under the raised stool and stares back at the embarrassed proprietor. The innkeeper's other hand offers the teapot instead of asking for payment. Strong foreground prop reveal, three distinct levels and connected gazes, no labels or jar writing.",
    all=["S00-02"], optional=True, highlight="保真问路生意露了底：掌柜坐着的凳子，正是旧桥拆下来的料。",
    camera="low foreground prop reveal under a lifted stool"),
])
