from main_story_authoring import n, chapter, option

# Plot revision 2: preserve stable task IDs and dependencies; illustrate the dramatic beat.
CHAPTER = chapter('S03', '永州柳子庙·背得走的与留下的', '金贵这次同行，有他自己的未竟心愿。一个专盯行囊的脚夫，把小算盘打成了火险，也逼众人分清什么才真正该护住。', 'S03-07', [
    n('S03-01', '江湾村头', '离村前，村民又往行囊里塞了一把菜。你把菜叶护得像宝贝，谁料这模样很快要惹来一双贪心的眼睛。', '告别江湾村，确认永州方向', [
        ('villager', '去永州沿旧堤，柳子庙那条路别错过。再带把菜！'),
        ('hero', '方位我记牢了，菜也快把我记牢了。'),
        ('narrator', '村民趁你转身，把一把青菜塞进竹篓。你忙回手护住，险些和自己的背带拧成结。'),
        ('you_bai', '好身法。江湖上少见这种背对敌人的擒菜手。'),
        ('hero', '这叫不辜负乡亲。不是护什么稀世珍宝。'),
        ('villager', '菜别闷着，图别淋着。都拿稳，比一路说谢强。'),
        ('hero', '记住了。你们新通的渠，也别忘了常清入口。'),
        ('narrator', '水声还在身后，旧道已伸向永州。你的行囊比来时重，脚下却比来时有底。'),
    ], '与江湾村民告别，沿已确认的旧道前往永州。',
    'Hero is already facing the road away from the village when a farmer tucks ONE bunch of greens into his bamboo basket. Hero reaches back awkwardly across his own strap to steady it, twisting with a comically earnest look over his shoulder. Youbai laughs from the open side. A broad restored canal behind them and one receding path ahead. No treasure, no formal farewell lineup, no overloaded mountain of gifts.',
    kind='Dialogue', all=[], any=[], optional=False, inside=False,
    options=[], hints=['先听清这段交流，留意告别江湾村，确认永州方向。', '这一步要做的是：告别江湾村，确认永州方向。', '把本段对话听完并确认结论：与江湾村民告别，沿已确认的旧道前往永州。'],
    cast=['villager', 'hero', 'you_bai'], mood='Affectionate slapstick with a small visual setup for the next conflict.', facts=['告别江湾村，确认永州方向', '与江湾村民告别，沿已确认的旧道前往永州。'],
    highlight='转身护住新塞的青菜，主角和背带拧成一团；为后面的‘贵重行李’误会埋伏笔。', camera='Rear three-quarter medium shot; basket and reaching-back arm dominate, village farmer extends greens from the edge, route opens ahead.'),
    n('S03-02', '前往永州', '金贵从路旁树影里伸出烟杆，先勾住了你的菜篮，再说自己恰好顺路。可他的鞋，分明刚从反方向赶来。', '与金贵重逢并约定同行', [
        ('jin_gui', '慢点走。你那把菜再晃两下，就自己去永州了。'),
        ('narrator', '一根烟杆轻轻托住松开的篮绳。草帽下，金贵还是那副没睡醒的笑。'),
        ('hero', '金贵？这么巧，你也顺路？'),
        ('jin_gui', '嗯，顺。绕了二十里来顺的。'),
        ('you_bai', '本座头回见把绕路说得这么坦荡的人。'),
        ('jin_gui', '柳子庙，我以前到门口三次，都被差事叫走。这回想进门坐一坐。'),
        ('hero', '那就同行。谁再叫你跑腿，先问问你自己愿不愿。'),
        ('jin_gui', '成。今日不赶别人的时辰。先把你这篮绳系好。'),
    ], '与金贵重逢，三人结伴前往柳子庙。',
    "On the road, Jin Gui steps out from a broad tree shadow and uses the curved end of his long bamboo pipe to support the hero's slipping basket cord. Hero is caught mid-stride, turning in startled recognition; Jin Gui's other hand raises his red-leaf straw hat a little, sleepy face breaking into a grin. Youbai hovers above the caught cord. Exact approved costumes, no smoking, no posed handshake, no fire.",
    kind='Dialogue', all=['S03-01'], any=[], optional=False, inside=False,
    options=[], hints=['先听清这段交流，留意与金贵重逢并约定同行。', '这一步要做的是：与金贵重逢并约定同行。', '把本段对话听完并确认结论：与金贵重逢，三人结伴前往柳子庙。'],
    cast=['jin_gui', 'hero', 'you_bai'], mood='An active, familiar reunion with understated warmth.', facts=['与金贵重逢并约定同行', '与金贵重逢，三人结伴前往柳子庙。'],
    highlight='重逢先由烟杆托住滑落菜篮发生，随后揭出金贵是特意绕路来完成自己的心愿。', camera='Side-on moving composition: pipe cuts in from a large tree shadow at left to catch the basket cord; hero turns mid-stride toward Jin Gui emerging lower behind.'),
    n('S03-03', '参天古柏密林', '热心脚夫的近道，地上有肉，草里有兽印，唯独他嘴里没有一句实话。金贵用烟杆挑起的那片肉，让笑脸一下绷住了。', '观察密林近道与脚夫的异常举动', [
        ('porter', '少侠，这边近！行李沉，我替你背。'),
        ('jin_gui', '近道长肉干？你们这儿的树挺懂待客。'),
        ('narrator', '金贵用烟杆挑起路旁肉片。草下几枚兽印围着它打转，脚夫的肩袋也漏着同样的油渍。'),
        ('porter', '山客掉的！山客嘛，走哪儿掉哪儿。'),
        ('hero', '那你怎么只盯着我的图袋，不问我们往哪儿去？'),
        ('you_bai', '他不是替你找近路。他是在替行李找新主人。'),
        ('jin_gui', '稳住。别急着追问，把自己的东西拿牢。'),
        ('hero', '嗯。先认清肉干和足印，再决定怎么走。'),
    ], '发现肉干与兽足印，识破近道有诈，准备应对密林遭遇。',
    "In a sparse cypress grove, Jin Gui lifts a single meat scrap with the end of his bamboo pipe. The grey-brown headcloth porter reacts by clapping a hand over the oily mouth of his shoulder bag, his salesman's smile stiffening. Hero has already drawn his own map pouch behind his hip, eyes tracking that guilty hand. Youbai peers from above the pipe. Two or three broad animal footprints on the soil support the clue; no battle, no fire, no generic group reading a map.",
    kind='Investigation', all=['S03-02'], any=[], optional=False, inside=False,
    options=[option('保管好行李，留意肉干与兽足印，拒绝交包', True, '近道的‘方便’是给脚夫留的。你们先保住行李，准备应对。'), option('把舆图交给脚夫，自己轻装上路', False, '金贵轻轻拨回你的手：先别把主线剧情打包送人。'), option('只看近道更短，立刻跟上', False, '短的是路，长的可能是后悔。再看看草丛里的东西。')], hints=['热心本身不是证据，看看近道上留下了什么。', '肉干碎屑、绕圈兽印和脚夫盯包的举动合在一起，很不对劲。', '选择‘保管好行李，留意肉干与兽足印，拒绝交包’。'],
    cast=['porter', 'jin_gui', 'hero', 'you_bai'], mood='Comic exposure with a new edge of suspicion.', facts=['观察密林近道与脚夫的异常举动', '发现肉干与兽足印，识破近道有诈，准备应对密林遭遇。'],
    highlight='金贵挑起肉干，脚夫下意识捂住同样漏油的袋口，动作直接出卖他。', camera="Tight triangular staging; lifted meat on pipe in foreground, porter's hand clamping his bag to one side, hero's suspicious profile on the other."),
    n('S03-04', '柳子庙', '终于踏进柳子庙，金贵却没急着坐。他看见后门的影子，便把留给自己的凳子，悄悄挪到了门边。', '在柳子庙核对旧志与地方图记', [
        ('hero', '找到了！旧志里这一段，正能接上潇水古图。'),
        ('you_bai', '慢翻，别把纸角当翻山的台阶。'),
        ('jin_gui', '你们看。我坐门边，透气。'),
        ('narrator', '金贵搬起凳子，却把凳脚卡在半开的后门旁。门外一道背袋影子顿了顿。'),
        ('hero', '你不是惦记这地方很久了？先过来看看。'),
        ('jin_gui', '看过一眼了。它没跑，我也不赶。倒是有人赶得很。'),
        ('you_bai', '后门？'),
        ('jin_gui', '嗯。书慢慢读，行李先放近些。别让这位熟人再替咱们‘分忧’。'),
    ], '在柳子庙找到旧志线索，并察觉堂后有异常动静。',
    'Inside the simple reading hall of Liuzi temple, Jin Gui quietly carries a plain stool sideways to wedge its leg near a half-open rear door. His head turns to watch a suspicious sack-shaped shadow beyond the threshold. In the foreground hero bends eagerly over an old gazetteer, with Youbai lighting a page, still unaware of that movement. Few broad beams, one table, one book. No Buddhist idol, no flames yet. Dramatic depth and contrasting attention, not three people calmly studying together.',
    kind='Dialogue', all=['S03-10'], any=[], optional=False, inside=True,
    options=[], hints=['先听清这段交流，留意在柳子庙核对旧志与地方图记。', '这一步要做的是：在柳子庙核对旧志与地方图记。', '把本段对话听完并确认结论：在柳子庙找到旧志线索，并察觉堂后有异常动静。'],
    cast=['hero', 'jin_gui', 'you_bai'], mood='Anticipation and quiet vigilance beneath apparent calm.', facts=['在柳子庙核对旧志与地方图记', '在柳子庙找到旧志线索，并察觉堂后有异常动静。'],
    highlight='金贵本想安心看书，却用凳子卡住后门；人物愿望与眼前警戒形成张力。', camera='Layered interior framing: hero absorbed over a book at the lower foreground; Jin Gui moving a stool into the rear doorway forms a separate diagonal focal plane.'),
    n('S03-05', '火险抢救', '你一眼看见了书，一把先拉住你的却是金贵。木架倒下时，‘护住旧志’终于有了先后次序。', '先保人身安全，再协力护住未燃书卷', [
        ('narrator', '火舌舔上外侧草帘，你刚要伸手去够高架旧志，金贵便扯住了你的后领。'),
        ('jin_gui', '先看脚下！架子歪了！'),
        ('hero', '书还在那儿——'),
        ('narrator', '木架向空处倾倒，尘灰扑落。金贵把你拉回稳地，自己也晃了一下，你立刻反手托住他的肩。'),
        ('you_bai', '人先站稳！外沿没着的书还能搬，里面的别硬闯！'),
        ('hero', '金贵，你带人退开。我接外沿书卷，大家把水递过来。'),
        ('jin_gui', '这回听清了。人不是包袱，别想着一趟全背走。'),
        ('hero', '明白。先保人，再一起护住够得着的书。'),
    ], '众人安全，火险得到控制，关键旧志与舆图记录被护住。',
    "The critical mutual-rescue instant in a small temple reading-hall fire: Jin Gui pulls the hero's back collar away from a tilting wooden shelf; hero has turned and braces Jin Gui's shoulder with his free hand so BOTH recover stable footing. A few intact book volumes stay on an accessible foreground bench, not scattered into confetti. Youbai anxiously lights the clear exit to one side. One broad orange flame shape on a distant curtain and a single pale smoke band, no injuries, no body dangling, no triumphant after-fire pose. Dynamic believable weight and distinct intent.",
    kind='Investigation', all=['S03-12'], any=[], optional=False, inside=True,
    options=[option('确认众人安全，协力转移外沿未燃书卷并控制火险', True, '分工终于比嘴快。人和关键书卷都保住了，火险也被控制。'), option('独自钻进浓烟里，把所有东西一次搬完', False, '幽白拦住你：英雄可以慢慢当，人不能拆开重装。先守住安全范围。'), option('先追脚夫理论，等争出道理再救场', False, '金贵把水桶塞过来：火不参加辩论，先让它安静。')], hints=['先确认人是否安全，再看哪些书卷能从安全的外沿转移。', '院里有空地、帮手、水桶和湿布；合理分工比独自冲进去有效。', '选择‘确认众人安全，协力转移外沿未燃书卷并控制火险’。'],
    cast=['hero', 'porter', 'jin_gui', 'you_bai'], mood='Urgent mutual care, the serious emotional high point of the chapter.', facts=['先保人身安全，再协力护住未燃书卷', '众人安全，火险得到控制，关键旧志与舆图记录被护住。'],
    highlight='金贵拉回抢书的主角，主角反手稳住金贵；两人互救，而非主角独自逞英雄。', camera='Strong diagonal close-medium action, characters leaning in opposite directions but linked at shoulder and collar; falling shelf behind them angles into an empty zone.'),
    n('S03-06', '永州简图', '永州简图补齐了，金贵却把行囊放下。他这次留在庙里，不是又接了谁的差事，是自己决定把这件事做完。', '整理获救旧志，补齐永州简图', [
        ('hero', '永州这几处接上了。你也跟我们往西南走？'),
        ('jin_gui', '我晚些。这里缺人收拾，书还没晾干。'),
        ('hero', '又替人跑腿？'),
        ('jin_gui', '这回是我自己想留下。好不容易进了门，总不能只负责路过一场火。'),
        ('narrator', '他把行囊搁在门内，顺手接住你递来的一卷书，动作比说话郑重。'),
        ('you_bai', '那本座不催。西南寨地的碑记，我们接着查。'),
        ('hero', '等你收拾妥当，下回换你挑地方，我来顺路。'),
        ('jin_gui', '二十里以内，算你真顺。路上稳些，后领不能回回有人拎。'),
    ], '永州简图已补齐，与金贵暂别，留下西南寨地碑记线索。',
    'After the fire is controlled, the temple doorway divides two chosen directions: Jin Gui inside sets his travel pouch down and accepts one saved book from the hero outside. Their hands nearly meet across the worn threshold; neither faces the viewer. Youbai hovers back, giving them room. One damp cloth and a small tidy stack of books establish cleanup, no active fire, no illness or deathbed. Warm held moment and practical affection.',
    kind='Dialogue', all=['S03-05'], any=[], optional=False, inside=True,
    options=[], hints=['先听清这段交流，留意整理获救旧志，补齐永州简图。', '这一步要做的是：整理获救旧志，补齐永州简图。', '把本段对话听完并确认结论：永州简图已补齐，与金贵暂别，留下西南寨地碑记线索。'],
    cast=['jin_gui', 'hero', 'you_bai'], mood='Bittersweet but hopeful separation between friends with their own choices.', facts=['整理获救旧志，补齐永州简图', '永州简图已补齐，与金贵暂别，留下西南寨地碑记线索。'],
    highlight='门槛两侧一递一接，金贵放下行囊主动留下，回收最初‘终于能坐一坐’的心愿。', camera='Quiet doorway composition, Jin Gui inside with basket set down at his feet, hero outside handing a book across the threshold; profiles and hands carry the emotion.'),
    n('S03-07', '土司寨遗痕', '碑记里一处眼熟的水槽刻痕，让幽白第一次主动承认：这条旧路，自己也曾记错。', '比对碑形与旧志，确认前往土司寨的线索', [
        ('hero', '碑记提到西南土司寨，旧水槽旁有这道刻痕。你认识？'),
        ('you_bai', '……认识。图里把它画到了寨北。'),
        ('hero', '碑记写的是旧址。后来迁寨，水槽也搬过。'),
        ('you_bai', '那一笔，大概还是本座催着抄的。嫌人家磨蹭，没等问完。'),
        ('narrator', '幽白靠近拓下的轮廓，看了好一会儿，终于把照明移向那处待改的标记。'),
        ('hero', '知道是哪一笔，就能再查。土司首领也许还记得你。'),
        ('you_bai', '记得最好。不记得，本座便从来意重新说。羊皮图的事，也当面求证。'),
        ('hero', '这句像个靠谱的带路前辈了。走，去问活人。'),
    ], '确认土司寨与羊皮图的线索，永州主干完成。',
    "Near a simple old stele, the small Youbai bends close to a plain rubbing sheet pinned against a board and deliberately illuminates one mismatched trough-shaped sketch. Hero, kneeling to pack the rubbing rather than holding up a map, pauses and watches the spirit's unusually earnest face. A broad weathered stone silhouette only, no readable inscriptions, no Tusi chief appearing early, no magic transformation. A tiny gesture carries a meaningful admission.",
    kind='Dialogue', all=['S03-06'], any=[], optional=False, inside=True,
    options=[], hints=['先听清这段交流，留意比对碑形与旧志，确认前往土司寨的线索。', '这一步要做的是：比对碑形与旧志，确认前往土司寨的线索。', '把本段对话听完并确认结论：确认土司寨与羊皮图的线索，永州主干完成。'],
    cast=['hero', 'you_bai'], mood="A sincere admission after the chapter's danger, restrained hope.", facts=['比对碑形与旧志，确认前往土司寨的线索', '确认土司寨与羊皮图的线索，永州主干完成。'],
    highlight='幽白不再遮住错处，而是主动照亮自己曾催抄的错误，延续第一章的成长。', camera="Low intimate view with tracing paper against a stone rubbing board, spirit's light catches a single mismatch while hero watches its face, not the map."),
    n('S03-08', '偶遇旧佣', '金贵摊开一张折了许多次的小纸：上面没有别人的差事，只有他给自己留的几处山水。', '听金贵讲重返旅途的缘由', [
        ('hero', '以前见你，总是东家一句话，你便跑得没影。'),
        ('jin_gui', '那时候走得多，看得少。路上每一刻，都算在别人的账里。'),
        ('you_bai', '如今自由了，可有什么雄图大志？'),
        ('jin_gui', '有。进柳子庙，坐着看完一页书。'),
        ('narrator', '他从帽内抽出一张折纸，展开又拢住。纸上只有几处粗略的山水轮廓。'),
        ('hero', '就这些？'),
        ('jin_gui', '先这些。往后想去哪，再添。可别替我一下排满。'),
        ('hero', '不排。你的路，当然由你自己挑。'),
    ], '了解金贵重返旅途的心愿，加深旧识情谊。',
    'A quiet roadside pause: Jin Gui tips back his broad red-leaf straw hat and pulls a small carefully folded travel sketch from its inner band, smiling to himself rather than performing for others. Hero sits on a low stone below his eye level and listens; Youbai floats in the open space on the opposite side. Only a few pictorial hill shapes on the paper. Clear asymmetry, relaxed individual poses, no smoke, no gifts, no grand map display.',
    kind='Dialogue', all=['S03-02'], any=[], optional=True, inside=False,
    options=[], hints=['先听清这段交流，留意听金贵讲重返旅途的缘由。', '这一步要做的是：听金贵讲重返旅途的缘由。', '把本段对话听完并确认结论：了解金贵重返旅途的心愿，加深旧识情谊。'],
    cast=['hero', 'jin_gui', 'you_bai'], mood="Small private joy and the dignity of choosing one's own journey.", facts=['听金贵讲重返旅途的缘由', '了解金贵重返旅途的心愿，加深旧识情谊。'],
    highlight='旧佣人拿出只属于自己的小小行程，第一次不需要替谁赶时间。', camera='Restful close profile: Jin Gui lifts his hat and slides out a small folded sketch, hero sits lower on a roadside stone, large plain sky above.'),
    n('S03-09', '假意相助', '脚夫声称见不得你负重，直到你递给他的包裹里，露出一截萝卜。那份侠义，立刻有了挑食的毛病。', '识别脚夫热心话术中的破绽', [
        ('porter', '少侠别多心，我就是看你背得辛苦，想帮个忙。'),
        ('hero', '那太好了。这袋最沉。'),
        ('narrator', '你把菜袋递过去。脚夫已经伸出的手，在看见萝卜头时硬生生拐了个弯。'),
        ('porter', '这个……不易碰坏。那边那只图袋更该仔细照料。'),
        ('jin_gui', '你这热心还分贵贱？'),
        ('porter', '我怕你弄丢重要东西！'),
        ('hero', '那讲讲路况。前面哪处滑，哪里绕？'),
        ('narrator', '脚夫答不上来，眼睛仍黏着图袋。你把两个包都收回自己身边。'),
    ], '识破脚夫回避路况、只盯贵重行李的破绽，保留警惕。',
    "Hero offers a small heavy cloth produce bag toward the porter. One unmistakable radish pokes from its mouth; the porter recoils his already-outstretched hand into an awkward fake pointing gesture toward the hero's separate secured map pouch. Jin Gui stands behind the porter with one raised eyebrow, pipe held down. Youbai watches the hand. Strong readable comic timing, no actual theft, no coin bag, no posed conversation lineup.",
    kind='Dialogue', all=['S03-03'], any=[], optional=True, inside=False,
    options=[], hints=['先听清这段交流，留意识别脚夫热心话术中的破绽。', '这一步要做的是：识别脚夫热心话术中的破绽。', '把本段对话听完并确认结论：识破脚夫回避路况、只盯贵重行李的破绽，保留警惕。'],
    cast=['porter', 'jin_gui', 'hero', 'you_bai'], mood='Dry comic exposure of a transparently selective kindness.', facts=['识别脚夫热心话术中的破绽', '识破脚夫回避路况、只盯贵重行李的破绽，保留警惕。'],
    highlight='伸手接包的姿势在萝卜露头时急转弯，贪念变成可读的身体动作。', camera="Comic close-medium side shot, protruding radish in the near foreground and porter's retracting hand form the focal pair, Jin Gui watches behind."),
    n('S03-10', '密林遇劫', '兽群循肉味扑来，脚夫趁乱伸手。金贵的烟杆这次勾住的不再是菜篮，而是差点被拽走的图袋。', '进入2-1，在剧情问号处击退被引来的兽群并保住行李', [
        ('narrator', '草丛一阵急响。猕猴抢向散落肉干，灰狼与野猪也循味逼近，脚夫的手已探到你的图袋旁。'),
        ('porter', '都说了，交给我保管！'),
        ('jin_gui', '你自己那袋肉，先保管明白吧。'),
        ('narrator', '你横竿挡住兽群，金贵贴到背篓旁，将露出卷轴的图袋护在怀里。脚夫伸手抓空，被金贵拦在一旁，连忙往树后缩。'),
        ('hero', '人和图都在，别追他。先把眼前这条路守住。'),
        ('you_bai', '这回本座看行李，你们应对兽群！'),
        ('jin_gui', '好。谁想顺手牵羊，先过我们这双眼睛。'),
        ('hero', '站稳再打，打完再算他的账。'),
    ], '兽群被击退，人和舆图保住；脚夫劫掠失手后逃走。',
    "In the cypress grove ambush, Jin Gui's bamboo pipe hooks the cord of the hero's map pouch back out of the porter's grasp. Hero catches the pouch behind one hip while bracing his own bamboo pole toward a low approaching gray wolf and boar; a macaque reaches for the meat lure to the side. The porter stumbles back empty-handed against a tree, not injured. Youbai guards the hero's basket. One continuous arc of cooperation and a failed grab, clear large animal silhouettes, no gore, no sword, no forest confetti, not an after-battle victory lineup.",
    kind='JourneyBattle', all=['S03-03'], any=[], optional=False, inside=False,
    options=[], hints=['这一步要实际应对密林遭遇，不能只听脚夫继续解释。', '进入2-1的剧情问号，沿用当前队伍击退敌人。', '从本节点进入对应关卡，在剧情问号完成任务战斗并获胜。'],
    cast=['porter', 'jin_gui', 'hero', 'you_bai'], mood='Brisk danger, clever teamwork and the trap turning against its maker.', facts=['进入2-1，在剧情问号处击退被引来的兽群并保住行李', '兽群被击退，人和舆图保住；脚夫劫掠失手后逃走。'],
    highlight='烟杆勾回图袋，主角转身接稳，脚夫抓空；把重逢时的小动作变成战斗中的关键配合。', camera='Sweeping diagonal action shot, rescued bag and pipe arc across center, hero braced toward incoming animals, porter recoils into a tree at far side.'),
    n('S03-11', '侥幸脱逃', '脚夫倒退着藏脚印，却忘了自己的肩袋挂在枝上。那截布带像一根箭头，比他的嘴诚实。', '追查脚夫逃走留下的痕迹', [
        ('hero', '人跑没了。脚印却一会儿朝这边，一会儿朝那边。'),
        ('jin_gui', '他倒着走了几步，想显得自己很会藏。'),
        ('you_bai', '此乃江湖秘术，原地增加可疑程度。'),
        ('narrator', '金贵拨开低枝，一截新扯下的布带挂在上头；断口正对着通向庙后的窄路。'),
        ('hero', '袋子都替他指路了。'),
        ('jin_gui', '新泥也带过去了。记方向，别为了追人把同行的又丢下。'),
        ('hero', '庙后可能有人靠近。我们先提醒、看好东西。'),
        ('you_bai', '把这一笔记清：他逃走了，可没说明他罢手了。'),
    ], '从布带和脚印确认脚夫逃向庙后，补充防备线索。',
    "After the ambush, Jin Gui lifts one low cypress branch with his pipe to reveal a fresh strip of the porter's grey-brown bag cloth snagged there. A short sequence of broad backwards footprints below abruptly turns toward the temple path. Hero half-crouches and looks along that revealed direction; Youbai peers underneath the hanging strip. The porter is absent, animals have gone. The visual punchline is a failed attempt to hide, not a generic footprint-reading pose.",
    kind='Dialogue', all=['S03-10'], any=[], optional=True, inside=True,
    options=[], hints=['先听清这段交流，留意追查脚夫逃走留下的痕迹。', '这一步要做的是：追查脚夫逃走留下的痕迹。', '把本段对话听完并确认结论：从布带和脚印确认脚夫逃向庙后，补充防备线索。'],
    cast=['jin_gui', 'hero', 'you_bai'], mood='A comic clue carrying a real warning.', facts=['追查脚夫逃走留下的痕迹', '从布带和脚印确认脚夫逃向庙后，补充防备线索。'],
    highlight='倒退脚印试图掩饰方向，挂在低枝上的布带却指出真实逃路。', camera='Ground-forward investigation framing: reversed footprints lead to a large dangling cloth strip, Jin Gui lifting the branch above, hero follows the revealed direction in profile.'),
    n('S03-12', '揽财纵火', '后堂起火，脚夫借乱搂包，却搂出半袋菜。你没让他空着手——一桶救火水，正好塞过去。', '识破柳庙纵火夺财的企图，组织救援', [
        ('narrator', '后堂窜起火光。脚夫缩着肩从侧边钻出，怀里紧搂一只顺手抓来的布袋。'),
        ('porter', '救东西要紧！我替你们先——'),
        ('narrator', '袋口一松，一把菜叶露了出来。他愣住的工夫，你把水桶推到他手里。'),
        ('hero', '好，救东西。先把这桶水送过去。'),
        ('jin_gui', '门边有新倒的灯油，火也是从你躲的地方起来的。还要装热心？'),
        ('porter', '我只想吓开你们，没想烧成这样……'),
        ('you_bai', '想得轻巧，着起来可不听你辩！人先退出来！'),
        ('hero', '现在提水、让路。账等人安全了，再一笔笔算。'),
    ], '识破脚夫纵火夺财的企图，众人开始有序控制火险。',
    "At the temple rear doorway as a small fire begins deeper inside, the porter is caught clutching a stolen produce bag whose green leaves spill visibly from the opening. Hero firmly places a full wooden water bucket into the porter's now-open arms; Jin Gui behind them pulls the door clear for people to leave. Youbai looks urgently toward the exit. One broad orange fire patch in the back, no dense smoke or catastrophe yet. The porter is exposed and forced to help, not forgiven or beaten.",
    kind='Dialogue', all=['S03-04'], any=[], optional=False, inside=True,
    options=[], hints=['先听清这段交流，留意识破柳庙纵火夺财的企图，组织救援。', '这一步要做的是：识破柳庙纵火夺财的企图，组织救援。', '把本段对话听完并确认结论：识破脚夫纵火夺财的企图，众人开始有序控制火险。'],
    cast=['hero', 'porter', 'jin_gui', 'you_bai'], mood='A sharp comic reversal under urgent real consequences.', facts=['识破柳庙纵火夺财的企图，组织救援', '识破脚夫纵火夺财的企图，众人开始有序控制火险。'],
    highlight='偷错菜袋的脚夫被当场塞入水桶，犯罪的借口转成必须实际承担的救火动作。', camera="Dynamic doorway medium shot; hero drives a water bucket into porter's startled arms, bag of greens sagging at his elbow, Jin Gui opens the exit behind."),
    n('S03-13', '余善尚存', '脚夫赔礼的话说得很快，湿书却翻得极慢。这一次，没人替他的悔意鼓掌，大家等着看他把活做完。', '让脚夫承担补救，确认归还与整理记录', [
        ('porter', '东西都在这儿，我没藏了。我赔不是……'),
        ('hero', '还回来是该做的。火烧坏的，也得担起来。'),
        ('jin_gui', '先别忙着保证。那页湿了，轻些揭，别扯。'),
        ('narrator', '脚夫粗手粗脚地停住，换用指腹一点点托起书角。险些裂开的纸终于完整落到晾板上。'),
        ('porter', '原来这一下，也能毁东西。'),
        ('you_bai', '你先前可毁得痛快。'),
        ('hero', '想补救，就留下慢慢做。不是说一句后悔，这事便翻篇了。'),
        ('porter', '我做。物件归谁、损了什么，都记下来，我认。'),
    ], '脚夫归还物品并留下整理书卷，以实际行动补救。',
    'During careful cleanup after the fire is extinguished, the stocky porter bends deeply over a low drying board, using both rough fingertips to support ONE fragile damp book page without tearing it. His face is intent and ashamed, not smiling for approval. Jin Gui points to where the page needs support; hero stands beyond the table with the returned belongings gathered, Youbai silently observes. Few intact books, no flames, no instant celebratory forgiveness, no readable text.',
    kind='Dialogue', all=['S03-05'], any=[], optional=True, inside=True,
    options=[], hints=['先听清这段交流，留意让脚夫承担补救，确认归还与整理记录。', '这一步要做的是：让脚夫承担补救，确认归还与整理记录。', '把本段对话听完并确认结论：脚夫归还物品并留下整理书卷，以实际行动补救。'],
    cast=['porter', 'hero', 'jin_gui', 'you_bai'], mood='Sober and tentative, responsibility expressed through patient work.', facts=['让脚夫承担补救，确认归还与整理记录', '脚夫归还物品并留下整理书卷，以实际行动补救。'],
    highlight='急着认错的人被迫慢下来，小心托住一页湿纸；用动作表达尚未完成的补救。', camera="Close low tabletop shot focused on the porter's oversized rough fingers supporting a fragile damp page, Jin Gui's guiding hand nearby, hero watches from the far edge."),
])
