from main_story_authoring import n, chapter, option

# Plot revision 2: preserve stable task IDs and dependencies; illustrate the dramatic beat.
CHAPTER = chapter('S02', '湘江潇水·这张图管不管饭', '船夫的生意经里藏着村里的难处。一条画错的水道，纸上只差一笔，田里却差一季饭。', 'S02-06', [
    n('S02-01', '湘江渡口', '幽白刚夸完图上水路四通八达，船夫便把船停在一段干渠旁：请它先把这条‘通’解释一下。', '询问前往江湾村的水陆路线', [
        ('boatman', '过江上船！去江湾村，水路陆路都能走，别跟着漂亮图走。'),
        ('you_bai', '什么叫漂亮图？此图水路四通——'),
        ('narrator', '船夫把竹篙往岸边一戳。图上那条宽阔支流，此刻只扬起一小股灰。'),
        ('hero', '八达先缓缓。前辈，它这儿通的是风。'),
        ('boatman', '正河水哗哗响，村里田渠却干着。抄图的人只管画蓝线，庄稼可不吃墨。'),
        ('you_bai', '也许是时令……'),
        ('hero', '那就问现在住这儿的人。江湾村怎么去？'),
        ('boatman', '坐船到村边，走路沿旧堤。先讲条件，再开船。'),
    ], '确认江湾村有水陆两种走法，并听闻水道异常。',
    "One decisive comic image at a ferry landing: the sturdy boatman drives the blunt bottom of his bamboo pole into a visibly DRY side ditch, raising one broad small puff of dust. The hero halfway unfolds his map and swivels his whole torso toward the evidence; Youbai's boast freezes on his face. A broad blue-green MAIN river remains clearly flowing behind the dry ditch. Strong diagonal pole, only three large character shapes, no repair yet.",
    kind='Dialogue', all=[], any=[], optional=False, inside=False,
    options=[], hints=['先听清这段交流，留意询问前往江湾村的水陆路线。', '这一步要做的是：询问前往江湾村的水陆路线。', '把本段对话听完并确认结论：确认江湾村有水陆两种走法，并听闻水道异常。'],
    cast=['boatman', 'hero', 'you_bai'], mood='A sharp comic interruption grounded in a real village problem.', facts=['询问前往江湾村的水陆路线', '确认江湾村有水陆两种走法，并听闻水道异常。'],
    highlight='竹篙戳中干渠，漂亮舆图被现实当场反驳。', camera='Low bank-level angle: bamboo pole and dry channel cut across the foreground, boatman towering on the left, hero twisted around with his map on the right.'),
    n('S02-02', '舌战船夫', '你准备砍船价，船夫却把伸出的手一翻，露出满掌泥痕。他想谈的条件，比一趟船钱重些。', '用已知路线与村情说服船夫讲清条件', [
        ('boatman', '逆风费力，顺水费心。去江湾村，还得答应我一件事。'),
        ('hero', '先说好，我不买船，也不接手祖传码头。'),
        ('boatman', '你们真肯查图，就别只在村口看一眼。那条渠，替我们查到底。'),
        ('narrator', '船夫摊开手，指缝还嵌着昨夜清渠留下的泥。'),
        ('you_bai', '你方才伸手，不是要加钱？'),
        ('boatman', '钱挣少了还能撑两趟船。田再旱下去，这一船人的饭找谁要？'),
        ('hero', '这事我们记下。水路和陆路各有什么线索，也请你讲清。'),
        ('boatman', '水路能问老行人，陆路能看旧堤。哪路都行，别让村里再白等。'),
    ], '船夫讲清两条路线，水路与陆路分支均可体验。',
    "At the ferry, the boatman turns one rough muddy palm upward into the space where the hero expected a money demand. His sleeves are rolled up; the hero's ready bargaining finger slowly lowers, mouth slightly open. Youbai peers down from the side, newly attentive. The palm is large but anatomically natural in the foreground, a coiled boat rope below; no coins, no handshake, no map held frontally. Warm restrained humanity.",
    kind='Dialogue', all=['S02-01'], any=[], optional=False, inside=False,
    options=[], hints=['先听清这段交流，留意用已知路线与村情说服船夫讲清条件。', '这一步要做的是：用已知路线与村情说服船夫讲清条件。', '把本段对话听完并确认结论：船夫讲清两条路线，水路与陆路分支均可体验。'],
    cast=['boatman', 'hero', 'you_bai'], mood='The joke stops for a beat; respect replaces suspicion.', facts=['用已知路线与村情说服船夫讲清条件', '船夫讲清两条路线，水路与陆路分支均可体验。'],
    highlight='被误认为讨价的手，翻过来是连夜清渠的泥痕。', camera="Intimate over-hero-shoulder framing. Boatman's open muddy palm is the large foreground focal shape, his face beyond it; hero's reaction is in profile."),
    n('S02-03', '船上施贫', '你递出干粮，老行人却拿起两根筷子，在船板上摆出了旧渠的来龙去脉。原来这趟船上还有位没挂招牌的行家。', '帮助同船老行人，听取上游水情', [
        ('poor_traveler', '赶路误了饭点，肚子比船橹还准时。'),
        ('hero', '我这儿有干粮。您先吃，不急着谢。'),
        ('boatman', '热水也有。老爷子年轻时修过这边的渠，问水找他就对了。'),
        ('poor_traveler', '修过几段罢了。借两根筷子，我给你们摆摆。'),
        ('narrator', '老人一手压着干粮，另一手把筷子斜接起来：一根是正河，一根是向田里落低的支渠。'),
        ('you_bai', '原来船上还藏着一位水路掌门。'),
        ('poor_traveler', '掌门也得吃饭。正河没断，是两根筷子相接这儿堵了。'),
        ('hero', '明白。这顿饭我请，这堂课我记。'),
    ], '老行人得到帮助，得知支渠堵塞而非整条河断流。',
    'Inside a stable small ferry, a dignified patched-blue-robed elderly traveler bends over two chopsticks placed in a joined branching shape on a plain boat plank. He pins his modest food parcel with an elbow while demonstrating the canal with his other hand. Hero crouches opposite, intensely following the tiny model; the boatman looks back over his shoulder without abandoning his pole, Youbai leans close. The old man actively teaches rather than receiving a ceremonial gift. One clean broad river band surrounds the boat.',
    kind='Dialogue', all=['S02-02'], any=[], optional=True, inside=False,
    options=[], hints=['先听清这段交流，留意帮助同船老行人，听取上游水情。', '这一步要做的是：帮助同船老行人，听取上游水情。', '把本段对话听完并确认结论：老行人得到帮助，得知支渠堵塞而非整条河断流。'],
    cast=['poor_traveler', 'hero', 'you_bai', 'boatman'], mood='Warm curiosity and the unexpected authority of lived experience.', facts=['帮助同船老行人，听取上游水情', '老行人得到帮助，得知支渠堵塞而非整条河断流。'],
    highlight='受助老人用两根筷子讲清水路，双方从施舍关系变成平等交换。', camera='Steep three-quarter overhead looking into the skiff, two chopsticks and a modest food parcel anchor the center, faces cluster at different heights around them.'),
    n('S02-04', '村头问询', '村民把新沟挖得笔直漂亮，偏偏水只往回流。幽白看了一眼坡，决定先把夸奖咽回去。', '通过村民与水痕了解断水位置', [
        ('villager', '这沟昨天刚挖，直不直？整不整齐？'),
        ('hero', '很直。可怎么一路往高处走？'),
        ('villager', '大家急，照着新抄的图就挖了。你看，倒桶水试试。'),
        ('narrator', '水刚倒下，便沿沟回流，绕到村民自己的鞋尖。'),
        ('you_bai', '这沟志向高远，只是水尚未练成轻功。'),
        ('hero', '先别加挖。旧渠入口在哪？那里原来能通水吗？'),
        ('villager', '旧堤转弯处。前些日子竹枝杂物冲下来，才开始断水。'),
        ('hero', '那就查旧入口。图错一笔，大家可要多挖好几天。'),
    ], '从陆路村头确认支渠入口与杂物淤堵的线索。',
    "A farmer tips a SMALL bucket into a new uphill ditch; the little ribbon of water visibly runs back toward his own shoes. He hops one foot up in surprise while hero squats off to the side tracing the wrong incline with a flat palm. Youbai hangs sideways above the slope in a wry pause. Low camera makes the channel's uphill angle obvious. This is a small failed test, not a flood, not restored irrigation.",
    kind='Dialogue', all=['S02-02'], any=[], optional=True, inside=False,
    options=[], hints=['先听清这段交流，留意通过村民与水痕了解断水位置。', '这一步要做的是：通过村民与水痕了解断水位置。', '把本段对话听完并确认结论：从陆路村头确认支渠入口与杂物淤堵的线索。'],
    cast=['villager', 'hero', 'you_bai'], mood='Physical comedy with a clear, readable piece of evidence.', facts=['通过村民与水痕了解断水位置', '从陆路村头确认支渠入口与杂物淤堵的线索。'],
    highlight='测试水流原路回到挖沟人的鞋边，一眼看清‘漂亮却逆坡’的错误。', camera='Ground-level along the ditch, broad returning water ribbon leads from the tipped bucket in the distance to a startled lifted shoe in the foreground.'),
    n('S02-05', '江湾村治水', '顺着水声找到旧渠口，竹枝把真正的入口堵得严严实实。拔掉这团塞子，比再挖十条漂亮新沟有用。', '进入1-3调查河道，判断并疏通支渠入口', [
        ('villager', '人都叫齐了。你说往哪挖，我们就往哪挖！'),
        ('hero', '先把锄头放放。今天少挖几下，也算帮忙。'),
        ('narrator', '低处旧支渠口挤着竹枝、落叶和淤泥；渠外正河仍在流。新挖的高沟反而朝坡上伸去。'),
        ('you_bai', '像不像一壶茶，壶嘴塞住了，大家忙着给壶盖开窗？'),
        ('villager', '那我昨天就是开窗开得最卖力的。'),
        ('hero', '别忙着怪谁。认准正河与田渠相接的地方，再一起动手。'),
        ('elder', '我守在下游看水。等你们清开，先放小股，别把渠岸冲坏。'),
        ('hero', '好。先把路还给水。'),
    ], '支渠入口被疏通，水重新流向农田；村长闻讯赶来查看，治水目标达成。',
    'The moment successful irrigation repair begins: hero and the farmer brace on dry banks and lift ONE compact tangled bamboo obstruction clear of the low original inlet. A controlled fresh ribbon of blue-green water curls underneath toward the fields. The village elder farther down holds up an acknowledging hand, Youbai has to bob aside from one broad harmless splash. Dynamic opposing body weights, cohesive silhouettes and one strong water curve; no scattered debris confetti, no dangerous flood, no formal success lineup.',
    kind='JourneyInvestigation', all=[], any=['S02-03', 'S02-04'], optional=False, inside=False,
    options=[option('清走旧支渠入口的竹枝落叶，疏通淤泥', True, '水终于找回了正经上班路线，顺着旧支渠流进田里。'), option('把新挖的高沟再往山坡上延长', False, '这条沟很有上进心，可惜水不配合。检查入口和地势。'), option('把正河拦住，等它自己转弯', False, '村长连连摆手：解决一条小渠，不必给全村加个大难题。')], hints=['先找‘正河有水、田渠没水’之间的断点。', '旧支渠入口被竹枝与淤泥堵住，旧渠地势向农田降低；新沟却逆坡。', '选择‘清走旧支渠入口的竹枝落叶，疏通淤泥’。'],
    cast=['hero', 'you_bai', 'villager', 'elder'], mood='A satisfying collective release, strenuous but joyful.', facts=['进入1-3调查河道，判断并疏通支渠入口', '支渠入口被疏通，水重新流向农田；村长闻讯赶来查看，治水目标达成。'],
    highlight='合力抽出堵口竹枝的一瞬，一股清水终于拐入旧渠；这是全章劳动的高潮。', camera='Oblique wide shot tight to the action: a large diagonal bamboo tangle being lifted, hero and farmer counterbalancing, water making a bold S curve below.'),
    n('S02-06', '潇水古图', '村长没有请出什么镇村宝卷，而是解开自己的袖口：真正能用的古图，早被汗水和田泥磨软了。', '结合实地水道修正潇水古图', [
        ('elder', '你们要找古图？在这儿。'),
        ('narrator', '村长解开袖口，取出一包磨软的油布。图上水线朴素，折痕却结结实实。'),
        ('you_bai', '就这么贴身揣着？不供个匣子？'),
        ('elder', '下田要用，供起来谁认沟？倒是那几张描金的抄本，越抄越不认得家了。'),
        ('hero', '湾渠、田沟……同一股水，乡里上下游叫法不同，被抄成了两条。'),
        ('elder', '对。水今天通了，这笔也该通。'),
        ('hero', '我把实地入口和两处叫法合注。往永州的旧道，也请您核一遍。'),
        ('elder', '沿下游去柳子庙，旧志和碑记还在。记不准的，到了再问。'),
    ], '潇水古图已核对补注，取得永州柳子庙的后续线索。',
    'The small village elder rolls his work sleeve back and draws a worn oilcloth map packet from its inner wrap. The soft folded paper almost slips; the hero seated on a low doorstep catches its bottom corner with one open hand. Youbai peers into the humble sleeve in surprise. A single restored water-channel shape lies beyond the doorstep. Emphasize cared-for utilitarian material and expressive hands, no gold treasure chest, no ceremonial presentation of a flat map to camera.',
    kind='Dialogue', all=['S02-05'], any=[], optional=False, inside=True,
    options=[], hints=['先听清这段交流，留意结合实地水道修正潇水古图。', '这一步要做的是：结合实地水道修正潇水古图。', '把本段对话听完并确认结论：潇水古图已核对补注，取得永州柳子庙的后续线索。'],
    cast=['elder', 'hero', 'you_bai'], mood='Affectionate discovery of value hidden in everyday use.', facts=['结合实地水道修正潇水古图', '潇水古图已核对补注，取得永州柳子庙的后续线索。'],
    highlight='村长从贴身袖包抽出磨软的实用古图，反转‘珍贵古图必有隆重仪式’。', camera="Close side view centered on the elder's worn sleeve and unfurling oilcloth, hero leaning in from a lower seated position, faces not symmetrically arranged."),
    n('S02-07', '呈谢纷纷', '村民的谢礼走了一圈，又回到参与清渠的人手里。幽白伸长脖子等夸奖，最后只分到一股葱香。', '接受村民谢意，说明共同治水的功劳', [
        ('villager', '自家菜，不值钱，路上添口热乎的！'),
        ('narrator', '一把青菜刚到你怀里，第二只菜篮便从另一边递来。你忙把第一把分回清渠的人。'),
        ('hero', '慢些慢些！我背的是行囊，不是移动菜市。'),
        ('you_bai', '本座全程督导，按理也该——'),
        ('villager', '那给前辈闻闻新葱？'),
        ('you_bai', '……芳香扑鼻，十分厚重。'),
        ('hero', '这水是大家一起通的。笔记里不能只写我们。'),
        ('villager', '成。记人随你，菜得带点。纸上的功劳又不能下锅。'),
    ], '与村民互致谢意，将共同疏渠的经历记入行旅笔记。',
    'A lively vegetable relay on the restored canal bank: two farmers approach from opposite edges with modest baskets, the hero in the center twists to pass a bunch of greens back to the first helper just as a second basket reaches him. His map stays safely tucked away. Youbai stretches toward a single scallion held up like an absurd award. Only four main figures, clear overlapping arms and distinct gestures, no huge food mountain and no posed gratitude ceremony.',
    kind='Dialogue', all=['S02-05'], any=[], optional=True, inside=True,
    options=[], hints=['先听清这段交流，留意接受村民谢意，说明共同治水的功劳。', '这一步要做的是：接受村民谢意，说明共同治水的功劳。', '把本段对话听完并确认结论：与村民互致谢意，将共同疏渠的经历记入行旅笔记。'],
    cast=['villager', 'hero', 'you_bai'], mood='Bustling affectionate comedy after shared hard work.', facts=['接受村民谢意，说明共同治水的功劳', '与村民互致谢意，将共同疏渠的经历记入行旅笔记。'],
    highlight='谢礼被主角顺手分回劳动者，形成热闹的人与菜的接力。', camera='Playful lateral close-medium shot: hero sandwiched between two opposing baskets, torso twisting as he passes one small vegetable bunch back.'),
    n('S02-08', '答谢呈图', '你问古图是谁画的，村长掰着手指数了半天：有人会写，有人不会写，但走过的路都在里面。', '听村长讲清古图的保存与流传', [
        ('hero', '村长，这张图的作图人叫什么？我想记清来处。'),
        ('elder', '最早那笔是我祖父。后来撑船的添水位，种田的改渠口，认字的替不认字的记。'),
        ('you_bai', '那落款岂不是比图还长？'),
        ('elder', '写不下就别只写一个大名。渠又不是某一个人挖的。'),
        ('narrator', '老人按住图角，指甲缝里的田泥和旧纸上的浅褐手印，竟有些相像。'),
        ('hero', '明白。记流传，也记每条说法是谁亲眼见的。'),
        ('elder', '错了就回来问。别把我们供成不许改的老神仙。'),
        ('you_bai', '这句话……本座记住了。'),
    ], '补记古图的来源与作图者口述，完善证据记录。',
    "A quiet human-scale composition: the elder's weathered fingertip rests beside one faded palm smudge on the old working map, while the hero pauses his brush above a separate small notebook to listen. The elder is in cropped profile, not facing camera; Youbai lowers close to the old trace with an unusually thoughtful expression. Only simple drawn river lines, no readable writing. Warm late light, broad clean tabletop and plenty of calm space.",
    kind='Dialogue', all=['S02-06'], any=[], optional=True, inside=False,
    options=[], hints=['先听清这段交流，留意听村长讲清古图的保存与流传。', '这一步要做的是：听村长讲清古图的保存与流传。', '把本段对话听完并确认结论：补记古图的来源与作图者口述，完善证据记录。'],
    cast=['elder', 'hero', 'you_bai'], mood='Reflective and intimate, a breath between larger comic scenes.', facts=['听村长讲清古图的保存与流传', '补记古图的来源与作图者口述，完善证据记录。'],
    highlight='带泥的指尖与古图旧手印相叠，幽白意识到守图也是守住许多普通人的经验。', camera="Quiet close-up across the tabletop: elder's weathered hand and hero's writing hand are primary; Youbai's small reflective face occupies one side, elder's profile partially visible."),
])
