"""Current user-approved rendering and canonical character-reference policy."""
from main_story_authoring import ROOT

STYLE_REFERENCE = ROOT / 'SourceArt/UI/StoryNodes/Redraw/S00/s00_03_1536.png'
PAINTERLY_STYLE = '''Create a NEW Chinese wuxia story illustration with a deliberately designed camera and character interaction.
Reference 1 supplies the approved first-chapter painterly ink-and-color finish ONLY. Do not copy its bridge, stairs, camera or poses into unrelated nodes. Subsequent references supply EXACT character identities. Magenta or checkerboard in reference cutouts is not part of the scene; omit it completely.
Use the project's graphic cartoon anatomy and distinct NPC shape language, clear variable-width dark brown brush silhouettes, broad matte muted color washes, sparse grey-green environmental shapes, warm pale paper and restrained broad pigment variation. Faces use clean designed planes, not realistic wrinkles or a generic anime/adult face. Keep small marks sparse. Do not turn this into the previously rejected sterile vector-flat style or into noisy paper speckles, miniature gravel, tiny foliage or dense crosshatching.
ENVIRONMENT DENSITY IS STRICT: mostly quiet blank warm paper behind the people, at most a few very faint broad scenery silhouettes and only the large props necessary for the action. No individual tree leaves, grass clumps, gravel, detailed mountain cliffs, moss flecks, white water foam or scratch-filled landscapes. Water is a broad continuous simple band; rocks are large calm shapes with two tonal planes. Graphically clean clothes with only a few meaningful folds. Do not reintroduce detail just because the panorama is wide.
ACTING: check body balance, planted feet, knees facing the same way as feet, shoulder/elbow/wrist continuity and correct fingers gripping props. Dynamic intentions can use simple natural poses; avoid giant foreshortened hands/boots, twisted knees, floating feet or detached arms. A quiet character stays quiet while another drives the action.
SPACE: simplicity does not mean a flat side-on lineup. Use purposeful foreground/middle/background overlap, scale changes and diagonal recession appropriate to the specific camera. Keep energy in the main action while using quiet shapes in the background. Human tracks are small traditional CLOTH-SHOE sole impressions, not bare feet with toes. Props must join correctly: the abbot's prayer beads form a closed continuous strand with ONE larger central bead.
The HERO must match the supplied 00_hero design: short broad rounded face and chin, thick bold eyebrows, large black-and-white eyes, swept-back compact black topknot, brown short jacket, grey-blue crossed collar, bamboo travel basket and bamboo pole. No adult-length handsome face, new hairstyle, sword or armor. Youbai is a single full blue-purple flame spirit with face, no limbs or human body. NPC identity references override generic age/face descriptions; do not reuse their bust pose in the action scene.
Compose a 3:1 landscape banner, intended display1536x512. Select the specified KEY MOMENT, not a posed success group. Follow the camera/staging below; one strong primary action, distinct body angles and eyelines, purposeful negative space, few necessary props. Faces, hands and focal props must be readable at small scale. Simple map pictograms only, no writing or UI, no speech bubbles, titles, watermark, frame or collage. Preserve all stated story facts and eventual result; never invent a failure, death, weapon or later-node event.
'''
