"""Contract checks for the isolated pure-2D desktop-training town map."""

from __future__ import annotations

import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TARGET_MAP = ROOT / "Content" / "GameXXK" / "Maps" / "L_DesktopTrainingHUD.umap"
SOURCE_MAP = ROOT / "Content" / "GameXXK" / "Maps" / "L_QingshanInn.umap"
BUILD_SCRIPT = ROOT / "Content" / "Python" / "gamexxk_create_desktop_training_hud_map.py"
LEVEL_FLOW = ROOT / "Source" / "GameXXK" / "Private" / "MVP" / "GameXXKLevelFlow.cpp"
REPORT = ROOT / "Saved" / "HarnessReports" / "desktop-training-hud-map.json"


class DesktopTrainingHUDMigrationContractTests(unittest.TestCase):
    def test_isolated_map_and_source_are_present(self) -> None:
        self.assertTrue(SOURCE_MAP.is_file(), SOURCE_MAP)
        self.assertTrue(TARGET_MAP.is_file(), TARGET_MAP)
        self.assertGreater(TARGET_MAP.stat().st_size, 0)

        script = BUILD_SCRIPT.read_text(encoding="utf-8")
        self.assertIn('SOURCE_MAP = "/Game/GameXXK/Maps/L_QingshanInn"', script)
        self.assertIn('TARGET_MAP = "/Game/GameXXK/Maps/L_DesktopTrainingHUD"', script)
        self.assertIn("HUD-only", script)

    def test_level_flow_selects_hud_map_and_keeps_3d_town_separate(self) -> None:
        source = LEVEL_FLOW.read_text(encoding="utf-8")
        self.assertIn('const FName DesktopTrainingHUDMap(TEXT("/Game/GameXXK/Maps/L_DesktopTrainingHUD"));', source)
        self.assertIn("return DesktopTrainingHUDMap;", source)
        self.assertIn("IsDesktopTrainingHUDMapPackage", source)
        self.assertIn("IsTownGameplayMapPackage", source)

        game_mode = (ROOT / "Source" / "GameXXK" / "Private" / "MVP" / "GameXXKMVPGameMode.cpp").read_text(encoding="utf-8")
        self.assertIn("EnsureQingshanTownRuntimeForDirectMap", game_mode)
        self.assertIn("return nullptr;", game_mode)

    def test_editor_report_when_available_contains_only_spawn_anchor(self) -> None:
        # Saved reports are generated by the editor and are intentionally not
        # required for a clean checkout.  When present, validate the stronger
        # actor-level evidence emitted by the map-cleaning script.
        if not REPORT.is_file():
            return
        payload = json.loads(REPORT.read_text(encoding="utf-8"))
        self.assertTrue(payload.get("ok"))
        self.assertEqual(payload.get("sourceMap"), "/Game/GameXXK/Maps/L_QingshanInn")
        self.assertEqual(payload.get("targetMap"), "/Game/GameXXK/Maps/L_DesktopTrainingHUD")
        self.assertEqual(payload.get("policy"), "HUD-only; no placed scenery/camera/light/character actors")
        kept = payload.get("keptActors", [])
        self.assertTrue(kept)
        self.assertTrue(all(item.get("class") in {"PlayerStart", "PlayerStartPIE"} for item in kept))


if __name__ == "__main__":
    unittest.main()
