"""Import the reviewed 61 story result illustrations and their own UI material only."""

def save_asset_with_texture_budget(*args, **kwargs):
    from gamexxk_texture_budget import save_loaded_asset
    return save_loaded_asset(*args, unreal_module=unreal, **kwargs)

import hashlib
import json
from pathlib import Path
import unreal

PROJECT = Path(__file__).resolve().parents[2]
DEST = '/Game/GameXXK/UI/StoryNodes'
manifest = json.loads((PROJECT / 'SourceArt/UI/StoryNodes/manifest.json').read_text(encoding='utf-8'))
campaign = json.loads((PROJECT / 'SourceAssets/Narrative/MainStory/campaign.json').read_text(encoding='utf-8'))
nodes = {n['id']: n for c in campaign['chapters'] for n in c['nodes']}
assert len(nodes) == 61 and set(manifest['nodes']) == set(nodes)
report_path = PROJECT / 'Saved/StorySystem/art-import-report.json'
previous = json.loads(report_path.read_text(encoding='utf-8')) if report_path.exists() else {}
previous_nodes = {r['id']: r for r in previous.get('textures', [])}
unreal.EditorAssetLibrary.make_directory(DEST)
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
results = []
for node_id, entry in sorted(manifest['nodes'].items()):
    assert entry['visual_review'] == 'pass', f'{node_id}: visual review is not complete'
    source = (PROJECT / entry['file']).resolve(strict=True)
    assert source.is_relative_to((PROJECT / 'SourceArt/UI/StoryNodes').resolve())
    assert hashlib.sha256(source.read_bytes()).hexdigest() == entry['sha256']
    expected = hashlib.sha256(json.dumps({'art': nodes[node_id]['art'], 'result': nodes[node_id]['result']}, ensure_ascii=False, sort_keys=True).encode('utf-8')).hexdigest()
    assert expected == entry['contract_sha256'], f'{node_id}: stale illustration contract'
    asset_path = entry['texture'].split('.')[0]
    exists = unreal.EditorAssetLibrary.does_asset_exist(asset_path)
    if not exists or previous_nodes.get(node_id, {}).get('sha256') != entry['sha256']:
        task = unreal.AssetImportTask()
        task.filename = str(source)
        task.destination_path = DEST
        task.destination_name = asset_path.rsplit('/', 1)[-1]
        task.automated = True
        # All paths in this dedicated folder are generated by this task.
        task.replace_existing = exists
        task.save = True
        asset_tools.import_asset_tasks([task])
    texture = unreal.load_asset(asset_path)
    assert isinstance(texture, unreal.Texture2D), f'{node_id}: import failed'
    texture.set_editor_property('lod_group', unreal.TextureGroup.TEXTUREGROUP_UI)
    texture.set_editor_property('compression_settings', unreal.TextureCompressionSettings.TC_EDITOR_ICON)
    texture.set_editor_property('mip_gen_settings', unreal.TextureMipGenSettings.TMGS_NO_MIPMAPS)
    texture.set_editor_property('srgb', True)
    texture.set_editor_property('never_stream', True)
    assert save_asset_with_texture_budget(texture)
    from gamexxk_texture_budget import source_size
    size = source_size(texture)
    assert size == entry['size'], f'{node_id}: texture dimensions changed'
    results.append({'id': node_id, 'asset': texture.get_path_name(), 'size': size, 'sha256': entry['sha256']})
    report_path.write_text(json.dumps({'textures': results, 'complete': False}, ensure_ascii=False, indent=2), encoding='utf-8')

lib = unreal.MaterialEditingLibrary
material_path = DEST + '/M_StoryIllustrationSoftEdge'
material = unreal.load_asset(material_path) if unreal.EditorAssetLibrary.does_asset_exist(material_path) else asset_tools.create_asset('M_StoryIllustrationSoftEdge', DEST, unreal.Material, unreal.MaterialFactoryNew())
material.set_editor_property('material_domain', unreal.MaterialDomain.MD_UI)
material.set_editor_property('blend_mode', unreal.BlendMode.BLEND_TRANSLUCENT)
for expression in lib.get_material_expressions(material):
    lib.delete_material_expression(material, expression)

def expression(cls):
    return lib.create_material_expression(material, cls)

def connect(a, a_pin, b, b_pin):
    target_pin = '' if b_pin == 'Input' else b_pin
    assert lib.connect_material_expressions(a, a_pin, b, target_pin), f'{a.get_name()} -> {b.get_name()}:{target_pin}'

def binary(cls, a, b):
    result = expression(cls)
    connect(a, '', result, 'A')
    connect(b, '', result, 'B')
    return result

texture_sample = expression(unreal.MaterialExpressionTextureSampleParameter2D)
texture_sample.set_editor_property('parameter_name', 'Illustration')
texture_sample.set_editor_property('texture', unreal.load_asset(results[0]['asset']))
uv = expression(unreal.MaterialExpressionTextureCoordinate)
edges = []
for channel, softness in [('r', 12.0), ('g', 10.0)]:
    component = expression(unreal.MaterialExpressionComponentMask)
    for c in ('r', 'g', 'b', 'a'):
        component.set_editor_property(c, c == channel)
    connect(uv, '', component, 'Input')
    inverse = expression(unreal.MaterialExpressionOneMinus)
    connect(component, '', inverse, 'Input')
    distance = binary(unreal.MaterialExpressionMin, component, inverse)
    factor = expression(unreal.MaterialExpressionConstant)
    factor.set_editor_property('r', softness)
    fade = expression(unreal.MaterialExpressionSaturate)
    connect(binary(unreal.MaterialExpressionMultiply, distance, factor), '', fade, 'Input')
    edges.append(fade)
opacity = binary(unreal.MaterialExpressionMultiply, edges[0], edges[1])
vertex = expression(unreal.MaterialExpressionVertexColor)
alpha = expression(unreal.MaterialExpressionMultiply)
connect(opacity, '', alpha, 'A')
connect(vertex, 'A', alpha, 'B')
assert lib.connect_material_property(texture_sample, 'RGB', unreal.MaterialProperty.MP_EMISSIVE_COLOR)
assert lib.connect_material_property(alpha, '', unreal.MaterialProperty.MP_OPACITY)
lib.layout_material_expressions(material)
lib.recompile_material(material)
assert save_asset_with_texture_budget(material)

# Change only the two approved visible names, retaining every stable ID and visual asset field.
renamed = []
catalog = unreal.load_asset('/Game/GameXXK/Narrative/Characters/DA_CharacterCatalog')
assert catalog, 'Existing character catalog is missing'
characters = list(catalog.get_editor_property('characters'))
for definition in characters:
    old = str(definition.get_editor_property('display_name'))
    if old not in ('月白', '琼梅儿'):
        continue
    definition.set_editor_property('display_name', unreal.Text({'月白': '幽白', '琼梅儿': '琼幺儿'}[old]))
    renamed.append(str(definition.get_editor_property('character_id')))
if renamed:
    catalog.set_editor_property('characters', characters)
    assert save_asset_with_texture_budget(catalog)
report = {'textures': results, 'material': material.get_path_name(), 'renamed_character_assets': renamed, 'complete': True}
report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
print(json.dumps({'imported': len(results), 'material': material.get_path_name(), 'report': str(report_path)}, ensure_ascii=False))
